### ISSUE TITLE
[Topup] Allow all logos to display when the page is loaded

### ISSUE THREAD

**Issue by itsinz** [torusresearch/torus-website#735] opened 2020-01-09 10:29 UTC
<img width="468" alt="Screenshot 2020-01-09 at 6 27 06 PM" src="https://user-images.githubusercontent.com/53069682/72059909-e2bf4a00-330d-11ea-886d-93030d770b01.png">
Have to click on each provider before the logos are revealed.

**Comment by chaitanyapotti** [comment] 2020-01-09 11:06
Duplicate of #673

**Closed by chaitanyapotti** 2020-01-09 11:06 UTC
