### ISSUE TITLE
[Activity] To show ERC 20 Tokens instead of Gas Fee

### ISSUE THREAD

**Issue by itsinz** [torusresearch/torus-website#520] opened 2019-10-25 04:04 UTC
<img width="1134" alt="Screenshot 2019-10-25 at 12 02 29 PM" src="https://user-images.githubusercontent.com/53069682/67542454-7629ab80-f71f-11e9-98ca-8283d03ede18.png">
Under 'Amount', to show 1KNC (the actual item being transferred) rather than 0.00016ETH (the gas fee for the transaction).

**Comment by chaitanyapotti** [comment] 2019-12-20 05:59
Duplicate of #654

**Closed by chaitanyapotti** 2019-12-20 05:59 UTC
