### ISSUE TITLE
Import account with ERC 721 will trigger 721 Badges

### ISSUE THREAD

**Issue by itsinz** [torusresearch/torus-website#1189] opened 2020-07-04 17:58 UTC
Situation:
- login with apple (new acc)
- import google acc
- badges being shown
this is no intended. ERC 721 from imported account should not trigger the "Get your first collectible" badge and modal.
Screenshot of the bade triggered once acc with ERC 721 is imported into new apple acc
<img width="1440" alt="Screenshot 2020-07-05 at 1 55 34 AM" src="https://user-images.githubusercontent.com/53069682/86518280-06012700-be63-11ea-979d-c13fdf1eba88.png">

**Comment by chaitanyapotti** [comment] 2020-07-09 08:51
Duplicate of #1127

**Closed by chaitanyapotti** 2020-07-09 08:51 UTC
Labels: bug
