### ISSUE TITLE
[Safari] Simplex top up does not work

### ISSUE THREAD

**Issue by hagiosssss** [torusresearch/torus-website#820] opened 2020-02-06 05:33 UTC
When window pops up, page turns from loading "testing.tor.us" page to "checkout.simplexcc.com" and changes back to a blank "testing.tor.us" page in a split second.
<img width="1263" alt="Screenshot 2020-02-06 at 1 26 32 PM" src="https://user-images.githubusercontent.com/51191261/73908444-aec34e80-48e4-11ea-84d7-a94d710cccf4.png">

**Comment by chaitanyapotti** [comment] 2020-02-06 06:23
Duplicate of #811

**Closed by chaitanyapotti** 2020-02-06 06:23 UTC
