### ISSUE TITLE
[iOS Chrome] Transaction Activity to show Send KNC/Tokens instead of Send ETH

### ISSUE THREAD

**Issue by itsinz** [torusresearch/torus-website#688] opened 2019-12-20 04:01 UTC
Situation : I sent KNC but on transaction activity it shows Send ETH
![ss1](https://user-images.githubusercontent.com/53069682/71229350-1ebf4a80-2320-11ea-8505-06bc5193f29d.jpg)
Supposed to look like this based on the respective type of transaction, ideally, when send KNC, should show KNC logo.
<img width="1039" alt="Screenshot 2019-12-20 at 11 59 52 AM" src="https://user-images.githubusercontent.com/53069682/71229425-6514a980-2320-11ea-87c2-8c357997a778.png">
Reference link : https://projects.invisionapp.com/d/main#/console/18774380/393810046/preview

**Comment by chaitanyapotti** [comment] 2019-12-20 05:25
Duplicate of #654

**Closed by chaitanyapotti** 2019-12-20 05:25 UTC
