### ISSUE TITLE
Weird numbers appearing when toggling between ETH and USD in the Transfer Page

### ISSUE THREAD

**Issue by elishatorus** [torusresearch/torus-website#1025] opened 2020-04-30 09:10 UTC
**Describe the bug**
When toggling between ETH and USD, the number being updated in the field is on a different conversion, and toggling the switch multiple times does not return the expected values, but changes the values instead.

**To Reproduce**
1. Go to the Transfer Page
2. Enter an amount
3. Click on USD, then ETH, then back to USD

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
- OS: Mac OS
- Browser: Chrome

![Screenshot 2020-04-30 at 5 02 53 PM](https://user-images.githubusercontent.com/51352241/80693341-714a1800-8b05-11ea-8c8f-9b7f4c74cb1b.png)
<img width="1218" alt="Screenshot 2020-04-30 at 5 51 11 PM" src="https://user-images.githubusercontent.com/51352241/80697272-537fb180-8b0b-11ea-99f9-94c165761dd7.png">

<img width="1198" alt="Screenshot 2020-04-30 at 5 51 19 PM" src="https://user-images.githubusercontent.com/51352241/80697278-55497500-8b0b-11ea-9517-ab51a458240c.png">

**Comment by chaitanyapotti** [comment] 2020-04-30 12:28
Duplicate of #1006

**Closed by chaitanyapotti** 2020-04-30 12:28 UTC
Labels: bug
