### ISSUE TITLE
[iOS Chrome] Skeleton placeholder - is not mobile version

### ISSUE THREAD

**Issue by itsinz** [torusresearch/torus-website#681] opened 2019-12-19 09:58 UTC
![2](https://user-images.githubusercontent.com/53069682/71163974-1ec03b80-2289-11ea-8c36-525fffe47dc0.jpg)
Skeleton placeholder is not the mobile format

**Comment by chaitanyapotti** [comment] 2019-12-19 14:05
Duplicate of #665 
You raised the same issue captain. we still didn't fix the last one

**Closed by chaitanyapotti** 2019-12-19 14:05 UTC
