### ISSUE TITLE
[Send ETH Popup] Loads in english and changes to Jap after a few seconds

### ISSUE THREAD

**Issue by itsinz** [torusresearch/torus-website#1158] opened 2020-06-23 10:34 UTC
When click on send ETH, popup loads in English and changes to Jap after a few seconds. 
To confirm that this is intended but loading too slow hence users can see the change..?
Ideal to just load in Jap
<img width="501" alt="Screenshot 2020-06-23 at 6 31 34 PM" src="https://user-images.githubusercontent.com/53069682/85393670-f7239600-b57f-11ea-89d3-fd153343bc86.png">
<img width="488" alt="Screenshot 2020-06-23 at 6 31 26 PM" src="https://user-images.githubusercontent.com/53069682/85393685-fb4fb380-b57f-11ea-973f-93aeacd05c60.png">

**Comment by chaitanyapotti** [comment] 2020-06-24 02:59
Duplicate of #1159

**Closed by chaitanyapotti** 2020-06-24 02:59 UTC
Labels: test
